language: rust

rust:
  - nightly
  - beta
  - stable

env:
  matrix:
    - FEATURES=''
    - FEATURES='default'
    - FEATURES='all'

script:
  - cargo build --verbose --all --no-default-features --features "$FEATURES"
  - cargo test --verbose --all --no-default-features --features "$FEATURES"

cache:
  - cargo

matrix:
  exclude:
    - rust: stable
      env: FEATURES='all'
